radiomand:
  build: ./radioman
  name: radiomand
  restart: always
  environment:
  - NO_LOCAL_PLAYLISTS=1
  volumes:
  - $HOME/Music:$HOME/Music
  - /etc/localtime:/etc/localtime:ro
  - ./playlists:/playlists
  - $HOME/playlists:$HOME/playlists
  - ./radioman/web:/web
  ports:
  - 4343:8000
  links:
  - liquidsoap

liquidsoap:
  image: moul/liquidsoap
  name: liquidsoap
  volumes:
  # command: /supervisor.sh liquidsoap -v --debug /liquidsoap/main.liq
  command: liquidsoap -v --debug /liquidsoap/main.liq
  user: liquidsoap
  restart: always
  volumes:
  - ./liquidsoap:/liquidsoap
  - $HOME/Music:$HOME/Music
  - /etc/localtime:/etc/localtime:ro
  - $HOME/playlists:$HOME/playlists
  - ./playlists:/playlists
  links:
  # - radioman
  - icecast
  ports:
  - 2300:2300
  environment:
  - ICECAST_SOURCE_PASSWORD

icecast:
  image: moul/icecast
  name: icecast
  restart: always
  volumes:
  - /etc/localtime:/etc/localtime:ro
  ports:
  - 4444:8000
  environment:
  - ICECAST_SOURCE_PASSWORD
  - ICECAST_ADMIN_PASSWORD
  - ICECAST_PASSWORD
  - ICECAST_RELAY_PASSWORD